// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plantopia.Data;

#nullable disable

namespace Plantopia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509101707_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Plantopia.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Plantopia.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Plantopia.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "A stunning tropical plant with iconic split leaves. Perfect for living rooms and offices.",
                            ImageUrl = "/images/Monstera Deliciosa.png",
                            Name = "Monstera Deliciosa",
                            Price = 850m
                        },
                        new
                        {
                            Id = 2,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "Low-maintenance plant perfect for any room. Thrives in low light.",
                            ImageUrl = "/images/snake.jpg",
                            Name = "Snake Plant",
                            Price = 450m
                        },
                        new
                        {
                            Id = 3,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "A dramatic indoor tree with large, waxy leaves. A statement piece for any space.",
                            ImageUrl = "/images/Fiddle Leaf Fig.jpg",
                            Name = "Fiddle Leaf Fig",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 4,
                            Badge = "Hot",
                            Category = "Hanging Plants",
                            Description = "Easy-care trailing plant ideal for shelves and hanging baskets.",
                            ImageUrl = "/images/Golden Pothos.png",
                            Name = "Golden Pothos",
                            Price = 350m
                        },
                        new
                        {
                            Id = 5,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "Beautiful patterned leaves with pink accents. Great for indoor spaces.",
                            ImageUrl = "/images/Aglaonema Pink Dalmatian.jpg",
                            Name = "Aglaonema Pink Dalmatian",
                            Price = 600m
                        },
                        new
                        {
                            Id = 6,
                            Badge = "New",
                            Category = "Succulents",
                            Description = "A compact rosette succulent with pastel tones. Perfect for desks and windowsills.",
                            ImageUrl = "/images/Echeveria.png",
                            Name = "Echeveria",
                            Price = 280m
                        },
                        new
                        {
                            Id = 7,
                            Badge = "Hot",
                            Category = "Outdoor Plants",
                            Description = "A graceful palm that brightens any outdoor space. Loves full sun.",
                            ImageUrl = "/images/Areca Palm.png",
                            Name = "Areca Palm",
                            Price = 399m
                        },
                        new
                        {
                            Id = 8,
                            Badge = "New",
                            Category = "Hanging Plants",
                            Description = "Lush, feathery fronds perfect for hanging baskets. Loves humidity.",
                            ImageUrl = "/images/Boston Fern.png",
                            Name = "Boston Fern",
                            Price = 320m
                        },
                        new
                        {
                            Id = 9,
                            Badge = "New",
                            Category = "Succulents",
                            Description = "Soft, velvety leaves with brown tips. A unique and charming succulent.",
                            ImageUrl = "/images/Panda Plant.png",
                            Name = "Panda Plant",
                            Price = 280m
                        },
                        new
                        {
                            Id = 10,
                            Badge = "Hot",
                            Category = "Hanging Plants",
                            Description = "One of the most adaptable houseplants. Great air purifier.",
                            ImageUrl = "/images/Spider Plant.png",
                            Name = "Spider Plant",
                            Price = 260m
                        },
                        new
                        {
                            Id = 11,
                            Badge = "Hot",
                            Category = "Succulents",
                            Description = "A small, easy-care succulent with striking striped leaves.",
                            ImageUrl = "/images/Haworthia.png",
                            Name = "Haworthia",
                            Price = 260m
                        },
                        new
                        {
                            Id = 12,
                            Badge = "Hot",
                            Category = "Hanging Plants",
                            Description = "A classic trailing vine perfect for hanging pots and trellises.",
                            ImageUrl = "/images/English Ivy.png",
                            Name = "English Ivy",
                            Price = 300m
                        },
                        new
                        {
                            Id = 13,
                            Badge = "Hot",
                            Category = "Outdoor Plants",
                            Description = "Vibrant flowering plant that thrives outdoors in full sun.",
                            ImageUrl = "/images/Bougainvillea.jpg",
                            Name = "Bougainvillea",
                            Price = 350m
                        },
                        new
                        {
                            Id = 14,
                            Badge = "New",
                            Category = "Outdoor Plants",
                            Description = "A popular flowering shrub commonly found in Filipino gardens.",
                            ImageUrl = "/images/Santan.png",
                            Name = "Santan",
                            Price = 149m
                        },
                        new
                        {
                            Id = 15,
                            Badge = "New",
                            Category = "Hanging Plants",
                            Description = "A fast-growing trailing plant with small, colorful leaves.",
                            ImageUrl = "/images/Turtle Vine.png",
                            Name = "Turtle Vine",
                            Price = 280m
                        },
                        new
                        {
                            Id = 16,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "Bold, arrow-shaped leaves that make a dramatic statement indoors.",
                            ImageUrl = "/images/Alocasia.jpg",
                            Name = "Alocasia",
                            Price = 750m
                        },
                        new
                        {
                            Id = 17,
                            Badge = "Hot",
                            Category = "Succulents",
                            Description = "A medicinal succulent known for its soothing gel. Easy to grow.",
                            ImageUrl = "/images/Aloe Vera.png",
                            Name = "Aloe Vera",
                            Price = 220m
                        },
                        new
                        {
                            Id = 18,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "Elegant white blooms and glossy leaves. Excellent air purifier.",
                            ImageUrl = "/images/Peace Lily.png",
                            Name = "Peace Lily",
                            Price = 480m
                        });
                });

            modelBuilder.Entity("Plantopia.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Plantopia.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("UserId", "PlantId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Plantopia.Models.Notification", b =>
                {
                    b.HasOne("Plantopia.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plantopia.Models.Wishlist", b =>
                {
                    b.HasOne("Plantopia.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantopia.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
