// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plantopia.Data;

#nullable disable

namespace Plantopia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509162659_MakeGCashNullable")]
    partial class MakeGCashNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Plantopia.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Plantopia.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("UserId", "PlantId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Plantopia.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Plantopia.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GCashName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GCashNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Plantopia.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<string>("PlantImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Plantopia.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "A stunning tropical plant with iconic split leaves. Perfect for living rooms and offices.",
                            DiscountPercent = 20,
                            ImageUrl = "/images/Monstera Deliciosa.png",
                            Name = "Monstera Deliciosa",
                            Price = 850m,
                            Rating = "4.9 (1.2k)",
                            Tags = "BestSeller,Sale"
                        },
                        new
                        {
                            Id = 2,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "Low-maintenance plant perfect for any room. Thrives in low light and purifies air.",
                            DiscountPercent = 15,
                            ImageUrl = "/images/Snake Plant.png",
                            Name = "Snake Plant",
                            Price = 450m,
                            Rating = "4.8 (980)",
                            Tags = "BestSeller,Sale"
                        },
                        new
                        {
                            Id = 3,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "A dramatic indoor tree with large, waxy leaves. A statement piece for any space.",
                            DiscountPercent = 25,
                            ImageUrl = "/images/Fiddle Leaf Fig.jpg",
                            Name = "Fiddle Leaf Fig",
                            Price = 1200m,
                            Rating = "4.6 (430)",
                            Tags = "BestSeller,Sale"
                        },
                        new
                        {
                            Id = 4,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "Beautiful patterned leaves with pink accents. Great for indoor spaces.",
                            DiscountPercent = 30,
                            ImageUrl = "/images/Aglaonema Pink Dalmatian.jpg",
                            Name = "Aglaonema Pink Dalmatian",
                            Price = 600m,
                            Rating = "4.7 (310)",
                            Tags = "NewArrival,Sale"
                        },
                        new
                        {
                            Id = 5,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "Bold, arrow-shaped leaves that make a dramatic statement indoors.",
                            ImageUrl = "/images/Alocasia.jpg",
                            Name = "Alocasia",
                            Price = 750m,
                            Rating = "4.5 (275)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 6,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "Elegant white blooms and glossy leaves. Excellent air purifier.",
                            ImageUrl = "/images/Peace Lily.png",
                            Name = "Peace Lily",
                            Price = 480m,
                            Rating = "4.8 (560)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 7,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "Striking heart-shaped leaves with vivid pink and green patterns. A tropical showstopper.",
                            ImageUrl = "/images/caladium.jpg",
                            Name = "Caladium",
                            Price = 520m,
                            Rating = "4.4 (185)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 8,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "Lush, heart-shaped leaves on long trailing vines. Easy to grow indoors.",
                            ImageUrl = "/images/Philodendron.png",
                            Name = "Philodendron",
                            Price = 850m,
                            Rating = "4.7 (390)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 9,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "Silvery-blue iridescent leaves that shimmer in indirect light. A rare and elegant pothos variety.",
                            ImageUrl = "/images/Cebu Blue Pothos.png",
                            Name = "Cebu Blue Pothos",
                            Price = 480m,
                            Rating = "4.6 (220)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 10,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "Braided trunk and glossy leaves. A popular symbol of good fortune and prosperity.",
                            ImageUrl = "/images/Money Tree.png",
                            Name = "Money Tree",
                            Price = 750m,
                            Rating = "4.7 (640)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 11,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "Delicate hole-filled leaves give this plant its charming Swiss cheese nickname.",
                            ImageUrl = "/images/Monstera Adansonii.jpg",
                            Name = "Monstera Adansonii",
                            Price = 550m,
                            Rating = "4.8 (475)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 12,
                            Badge = "New",
                            Category = "Indoor Plants",
                            Description = "A bonsai-style ficus with a thick, twisted root base. A living piece of art.",
                            ImageUrl = "/images/Ficus Ginseng.jpg",
                            Name = "Ficus Ginseng",
                            Price = 1100m,
                            Rating = "4.5 (160)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 13,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "Glossy dark green leaves that thrive in low light. Practically indestructible.",
                            ImageUrl = "/images/ZZ Plant.png",
                            Name = "ZZ Plant",
                            Price = 520m,
                            Rating = "4.9 (870)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 14,
                            Badge = "Hot",
                            Category = "Indoor Plants",
                            Description = "Deep burgundy and green leaves with a waxy finish. A bold and easy-care indoor tree.",
                            ImageUrl = "/images/Rubber Plant.png",
                            Name = "Rubber Plant",
                            Price = 680m,
                            Rating = "4.6 (340)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 15,
                            Badge = "Hot",
                            Category = "Outdoor Plants",
                            Description = "A graceful palm that brightens any outdoor space. Loves full sun.",
                            ImageUrl = "/images/Areca Palm.png",
                            Name = "Areca Palm",
                            Price = 399m,
                            Rating = "4.7 (510)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 16,
                            Badge = "Hot",
                            Category = "Outdoor Plants",
                            Description = "Vibrant flowering plant that thrives outdoors in full sun.",
                            ImageUrl = "/images/Bougainvillea.png",
                            Name = "Bougainvillea",
                            Price = 350m,
                            Rating = "4.8 (720)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 17,
                            Badge = "New",
                            Category = "Outdoor Plants",
                            Description = "A popular flowering shrub commonly found in Filipino gardens.",
                            ImageUrl = "/images/Santan.png",
                            Name = "Santan",
                            Price = 149m,
                            Rating = "4.5 (230)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 18,
                            Badge = "Hot",
                            Category = "Outdoor Plants",
                            Description = "Fragrant tropical blooms in white, pink, and yellow. A classic Filipino garden favorite.",
                            ImageUrl = "/images/Calachuchi.png",
                            Name = "Calachuchi",
                            Price = 320m,
                            Rating = "4.6 (290)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 19,
                            Badge = "Hot",
                            Category = "Outdoor Plants",
                            Description = "Brilliant red blooms that attract butterflies. The iconic Philippine garden flower.",
                            ImageUrl = "/images/Gumamela.png",
                            Name = "Gumamela",
                            Price = 180m,
                            Rating = "4.5 (415)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 20,
                            Badge = "New",
                            Category = "Outdoor Plants",
                            Description = "Compact flowering shrub with clusters of bright orange-red blooms. Great for borders.",
                            ImageUrl = "/images/dwarf-ixora.jpg",
                            Name = "Dwarf Ixora",
                            Price = 199m,
                            Rating = "4.3 (145)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 21,
                            Badge = "New",
                            Category = "Outdoor Plants",
                            Description = "The Philippine national flower, known for its sweet fragrance and delicate white petals.",
                            ImageUrl = "/images/sampaguita.jpg",
                            Name = "Sampaguita",
                            Price = 160m,
                            Rating = "4.7 (380)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 22,
                            Badge = "New",
                            Category = "Outdoor Plants",
                            Description = "Produces intensely fragrant yellow flowers used in perfumes and aromatherapy.",
                            ImageUrl = "/images/ylang-ylang.jpg",
                            Name = "Ylang-Ylang",
                            Price = 280m,
                            Rating = "4.4 (170)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 23,
                            Badge = "Hot",
                            Category = "Outdoor Plants",
                            Description = "Striped green and yellow leaves on a tall cane. A popular good-luck plant in Filipino homes.",
                            ImageUrl = "/images/Fortune Plant.png",
                            Name = "Fortune Plant",
                            Price = 450m,
                            Rating = "4.6 (330)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 24,
                            Badge = "Hot",
                            Category = "Outdoor Plants",
                            Description = "Fragrant leaves used widely in Filipino cooking. Also a natural air freshener.",
                            ImageUrl = "/images/pandan.jpg",
                            Name = "Pandan",
                            Price = 120m,
                            Rating = "4.8 (600)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 25,
                            Badge = "New",
                            Category = "Succulents",
                            Description = "A compact rosette succulent with pastel tones. Perfect for desks and windowsills.",
                            DiscountPercent = 15,
                            ImageUrl = "/images/Echeveria.png",
                            Name = "Echeveria",
                            Price = 280m,
                            Rating = "4.6 (320)",
                            Tags = "NewArrival,Sale"
                        },
                        new
                        {
                            Id = 26,
                            Badge = "New",
                            Category = "Succulents",
                            Description = "Soft, velvety leaves with brown tips. A unique and charming succulent.",
                            ImageUrl = "/images/Panda Plant.png",
                            Name = "Panda Plant",
                            Price = 280m,
                            Rating = "4.4 (195)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 27,
                            Badge = "Hot",
                            Category = "Succulents",
                            Description = "A small, easy-care succulent with striking striped leaves.",
                            ImageUrl = "/images/Haworthia.png",
                            Name = "Haworthia",
                            Price = 260m,
                            Rating = "4.7 (410)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 28,
                            Badge = "Hot",
                            Category = "Succulents",
                            Description = "A medicinal succulent known for its soothing gel. Easy to grow.",
                            ImageUrl = "/images/Aloe Vera.png",
                            Name = "Aloe Vera",
                            Price = 220m,
                            Rating = "4.9 (1.1k)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 29,
                            Badge = "New",
                            Category = "Succulents",
                            Description = "A round golden-spined cactus perfect for sunny windowsills and outdoor rock gardens.",
                            ImageUrl = "/images/Golden Barrel Cactus.png",
                            Name = "Golden Barrel Cactus",
                            Price = 350m,
                            Rating = "4.3 (125)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 30,
                            Badge = "New",
                            Category = "Succulents",
                            Description = "Cascading strands of bead-like leaves. A stunning and unique trailing succulent.",
                            ImageUrl = "/images/String of Pearls.png",
                            Name = "String of Pearls",
                            Price = 380m,
                            Rating = "4.5 (290)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 31,
                            Badge = "Hot",
                            Category = "Succulents",
                            Description = "A curated mix of colorful succulent varieties. Perfect starter set for new plant parents.",
                            DiscountPercent = 20,
                            ImageUrl = "/images/succulent.jpg",
                            Name = "Succulent Mix",
                            Price = 199m,
                            Rating = "4.6 (520)",
                            Tags = "Sale"
                        },
                        new
                        {
                            Id = 32,
                            Badge = "Hot",
                            Category = "Hanging Plants",
                            Description = "Easy-care trailing plant ideal for shelves and hanging baskets.",
                            DiscountPercent = 20,
                            ImageUrl = "/images/Golden Pothos.png",
                            Name = "Golden Pothos",
                            Price = 350m,
                            Rating = "4.8 (890)",
                            Tags = "BestSeller,Sale"
                        },
                        new
                        {
                            Id = 33,
                            Badge = "New",
                            Category = "Hanging Plants",
                            Description = "Lush, feathery fronds perfect for hanging baskets. Loves humidity.",
                            ImageUrl = "/images/Boston Fern.png",
                            Name = "Boston Fern",
                            Price = 320m,
                            Rating = "4.5 (275)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 34,
                            Badge = "Hot",
                            Category = "Hanging Plants",
                            Description = "One of the most adaptable houseplants. Great air purifier.",
                            ImageUrl = "/images/Spider Plant.png",
                            Name = "Spider Plant",
                            Price = 260m,
                            Rating = "4.7 (680)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 35,
                            Badge = "Hot",
                            Category = "Hanging Plants",
                            Description = "A classic trailing vine perfect for hanging pots and trellises.",
                            ImageUrl = "/images/English Ivy.png",
                            Name = "English Ivy",
                            Price = 300m,
                            Rating = "4.6 (445)",
                            Tags = "BestSeller"
                        },
                        new
                        {
                            Id = 36,
                            Badge = "New",
                            Category = "Hanging Plants",
                            Description = "A fast-growing trailing plant with small, colorful leaves.",
                            ImageUrl = "/images/Turtle Vine.png",
                            Name = "Turtle Vine",
                            Price = 280m,
                            Rating = "4.4 (160)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 37,
                            Badge = "New",
                            Category = "Hanging Plants",
                            Description = "Delicate heart-shaped leaves on long trailing vines. A romantic and elegant hanging plant.",
                            ImageUrl = "/images/String hearts.jpg",
                            Name = "String of Hearts",
                            Price = 650m,
                            Rating = "4.8 (510)",
                            Tags = "NewArrival"
                        },
                        new
                        {
                            Id = 38,
                            Badge = "Hot",
                            Category = "Hanging Plants",
                            Description = "Thick glossy oval leaves on woody stems. A symbol of good luck and prosperity.",
                            ImageUrl = "/images/Jade Plant.png",
                            Name = "Jade Plant",
                            Price = 390m,
                            Rating = "4.6 (360)",
                            Tags = "BestSeller"
                        });
                });

            modelBuilder.Entity("Plantopia.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Plantopia.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.HasIndex("UserId", "PlantId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Plantopia.Models.CartItem", b =>
                {
                    b.HasOne("Plantopia.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantopia.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plantopia.Models.Notification", b =>
                {
                    b.HasOne("Plantopia.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plantopia.Models.Order", b =>
                {
                    b.HasOne("Plantopia.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plantopia.Models.OrderItem", b =>
                {
                    b.HasOne("Plantopia.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantopia.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Plantopia.Models.Wishlist", b =>
                {
                    b.HasOne("Plantopia.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantopia.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Plantopia.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
